INSERT INTO recipe (name, category, kind, cook) VALUES ('Überbackenes Baguette','Backen','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Burger (selbstgemacht)','Fleisch','Not veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Empanadas','Fleisch','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Frikadellen','Fleisch','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Hot Dogs','Fleisch','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Pommes mit Nürnbergern','Fleisch','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gnocchi Hackpfanne','Gnocchi','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gnocchi Zucchini und Tomate','Gnocchi','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Bratkartoffeln','Kartoffel','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kartoffelbrei','Kartoffel','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kartoffelgratin','Kartoffel','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kartoffeln mit Quark','Kartoffel','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Knoblauchkartoffeln','Kartoffel','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Smashed Potatos','Kartoffel','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Pommes','Kartoffel','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Buchstaben-/Sternchensuppe','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gemüse Nudelpfanne','Nudeln','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kirschtomatennudeln','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Lasagne','Nudeln','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Linsenbolognese','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Maccharoni Auflauf','Nudeln','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudel-Brokkoli-Auflauf','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudel-Gratin (Knorr)','Nudeln','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln Aglio e Olio','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln Bolognese','Nudeln','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln mit Ei','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln mit Haschee','Nudeln','Not veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln mit Pesto (+ Gemüse)','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln mit Tomaten, Champignons, Käse,…','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Nudeln mit Tomatensoße','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Salbeinudeln','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Spaghetti Carbonara','Nudeln','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Spaghetti Pomodorini (L''Osteria Style)','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Spätzle mit Ei','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Spätzlepfanne mit Pilzen und Lauch','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Tagliatelle mit Pilzen in Currysoße','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Tortellini Salat','Nudeln','Not veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Überbackene Nudeln mit Tomatensahnesoße','Nudeln','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Vegetarische Tortellini-Pfanne','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Zitronenspagetti','Nudeln','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gefüllte Paprika','Reis','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gemüsereispfanne','Reis','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Mango-Kichererbsen-Curry','Reis','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Reis mit Erdnusssoße (Hähnchen Saté)','Reis','YN','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Reis mit Süßsauersoße','Reis','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Reispfanne','Reis','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Veganer Curryreis','Reis','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Salat','Salat','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gemüsesuppe','Suppe','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kartoffel-Kohl-Hack-Suppe','Suppe','Veggie','Lena');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Tomatensuppe','Suppe','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Milchreis','Süß','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Pfannkuchen','Süß','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Bistro Baguettes','TK','YN',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Knoblauchecken','TK','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Minipizzen','TK','YN',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Pizza (TK o. selbstgemacht)','TK','YN',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Falafel','Veggie','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gemüsesticks','Veggie','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Gemüsetaler','Veggie','Veggie',NULL);
INSERT INTO recipe (name, category, kind, cook) VALUES ('Kidneybohnen Burger','Veggie','Veggie','Marc');
INSERT INTO recipe (name, category, kind, cook) VALUES ('Wraps',NULL,'YN','Lena');
