version: '3'
services:
    web:
      image: nginx:1.25.1
      volumes:
          #- "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./html:/var/www/html"
      ports:
          - "8080:80"
          - "8443:443"
      restart: always
      depends_on:
          - php
    php:
      image: php:8.2-fpm
      restart: always
      volumes:
          #- "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
          - "./html:/var/www/html"