version: '3'
services:
    web:
        image: nginx:1.25.1
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./html:/var/www/html"
        ports:
            - "8080:80"
            - "8443:443"
        restart: always
        depends_on:
            - php
    php:
        image: php:8.2-fpm-pdo
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/php.ini"
            - "./html:/var/www/html"
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: passw0rd
        ports:
            - "5432:5432"
