FROM php:8.2-fpm
RUN apt-get update && apt-get install -y \
        libpq-dev \
		libfreetype-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
	&& docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pgsql pdo_pgsql